/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#fcf9f5",
        "surface-dim": "#dcdad6",
        "surface-bright": "#fcf9f5",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3ef",
        "surface-container": "#f0ede9",
        "surface-container-high": "#eae8e4",
        "surface-container-highest": "#e5e2de",
        "on-surface": "#1c1c1a",
        "on-surface-variant": "#4d4635",
        "inverse-surface": "#31302e",
        "inverse-on-surface": "#f3f0ec",
        "outline": "#7f7663",
        "outline-variant": "#d0c5af",
        "surface-tint": "#735c00",
        "primary": "#735c00",
        "on-primary": "#ffffff",
        "primary-container": "#d4af37",
        "on-primary-container": "#554300",
        "inverse-primary": "#e9c349",
        "secondary": "#5f5e5d",
        "on-secondary": "#ffffff",
        "secondary-container": "#e4e2e0",
        "on-secondary-container": "#656463",
        "tertiary": "#605e5b",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#b5b2ae",
        "on-tertiary-container": "#464541",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffe088",
        "primary-fixed-dim": "#e9c349",
        "on-primary-fixed": "#241a00",
        "on-primary-fixed-variant": "#574500",
        "secondary-fixed": "#e4e2e0",
        "secondary-fixed-dim": "#c8c6c4",
        "on-secondary-fixed": "#1b1c1b",
        "on-secondary-fixed-variant": "#474745",
        "tertiary-fixed": "#e6e2dd",
        "tertiary-fixed-dim": "#c9c6c1",
        "on-tertiary-fixed": "#1c1c19",
        "on-tertiary-fixed-variant": "#484743",
        "background": "#fcf9f5",
        "on-background": "#1c1c1a",
        "surface-variant": "#e5e2de",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "container-max": "1280px",
        "section-gap": "120px",
        "margin-desktop": "64px",
        "unit": "8px",
        "gutter": "24px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "headline-lg": ["Libre Caslon Text", "serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "button": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Libre Caslon Text", "serif"],
        "display-lg-mobile": ["Libre Caslon Text", "serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Libre Caslon Text", "serif"],
        "label-caps": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "button": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "400" }],
        "display-lg-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}
