/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#f5f5fc",
        "surface-dim": "#d6d6dc",
        "surface-bright": "#f5f5fc",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#efeff6",
        "surface-container": "#e9e9f0",
        "surface-container-high": "#e4e4ea",
        "surface-container-highest": "#dedee5",
        "on-surface": "#1a1a1c",
        "on-surface-variant": "#35354d",
        "inverse-surface": "#2e2e31",
        "inverse-on-surface": "#ecf0f3",
        "outline": "#63637f",
        "outline-variant": "#afafd0",
        "surface-tint": "#1B1464",
        "primary": "#1B1464",
        "on-primary": "#ffffff",
        "primary-container": "#3D35A0",
        "on-primary-container": "#E0DEFF",
        "inverse-primary": "#C4C0FF",
        "secondary": "#5d5e5f",
        "on-secondary": "#ffffff",
        "secondary-container": "#e0e2e4",
        "on-secondary-container": "#636465",
        "tertiary": "#5b5e60",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#aeb2b5",
        "on-tertiary-container": "#414546",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#E0DEFF",
        "primary-fixed-dim": "#C4C0FF",
        "on-primary-fixed": "#0A0047",
        "on-primary-fixed-variant": "#2D2591",
        "secondary-fixed": "#e0e2e4",
        "secondary-fixed-dim": "#c4c6c8",
        "on-secondary-fixed": "#1b1c1b",
        "on-secondary-fixed-variant": "#454745",
        "tertiary-fixed": "#dde2e6",
        "tertiary-fixed-dim": "#c1c6c9",
        "on-tertiary-fixed": "#191c1c",
        "on-tertiary-fixed-variant": "#434748",
        "background": "#f5f5fc",
        "on-background": "#1a1a1c",
        "surface-variant": "#dedee5",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "container-max": "1280px",
        "section-gap": "120px",
        "margin-desktop": "64px",
        "unit": "8px",
        "gutter": "24px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "headline-lg": ["Libre Caslon Text", "serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "button": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Libre Caslon Text", "serif"],
        "display-lg-mobile": ["Libre Caslon Text", "serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Libre Caslon Text", "serif"],
        "label-caps": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "button": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "400" }],
        "display-lg-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}
